### ISSUE TITLE
在实验详情中，不论是否执行实验，一直都显示未执行

### ISSUE THREAD

**Issue by zandwang** [chaosblade-io/chaosblade-box-fe#15]
在实验详情中，不论是否执行实验，一直都显示未执行
![image](https://user-images.githubusercontent.com/80032752/110056886-8a150100-7d9a-11eb-86b9-de3d8fe55322.png)
经排查，应该是前后端字段没对齐，前端在list页面和detail页面取的是不同的字段
list
![image](https://user-images.githubusercontent.com/80032752/110056993-b9c40900-7d9a-11eb-965b-c35b416acd9a.png)
detail
![image](https://user-images.githubusercontent.com/80032752/110057017-c3e60780-7d9a-11eb-9a67-2ad1fe555443.png)

后端在这两个接口都是返回的lastTaskStartTime

**Comment by MandssS** [comment]
好的，我们会尽快修复，如果方便，你这边也可以直接提pr

**Comment by MandssS** [comment]
你可以使用新版本：1.0.0，不存在这个问题
